# TODO (requires Windows runner)
#run_pester_tests:
#  before_script:
#    - Install-Module -Name Pester -Force
#    - Install-Module -Name 7Zip4PowerShell -Force
#    - Import-Module "Pester" -Force
#    - Import-Module "7Zip4PowerShell" -Force
#  stage: test
#  script:
#    - Invoke-Pester -CI
#  coverage: /Covered (\d+\.\d+%)/
#  variables:
#    POWERSHELL_TELEMETRY_OPTOUT: 1
#  tags:
#   - windows

# TODO
#create_installer:
#  stage: deploy
#  trigger:
#    project: perun-windows/services-installer
#    strategy: depend
#  only:
#    - master
