# TODO (requires Windows runner)
#run_pester_tests:
#  before_script:
#    - Install-Module -Name Pester -Force
#    - Install-Module -Name 7Zip4PowerShell -Force
#    - Import-Module "Pester" -Force
#    - Import-Module "7Zip4PowerShell" -Force
#  stage: test
#  script:
#    - Invoke-Pester -CI
#  coverage: /Covered (\d+\.\d+%)/
#  variables:
#    POWERSHELL_TELEMETRY_OPTOUT: 1
#  tags:
#   - windows

# see https://www.benjaminrancourt.ca/lint-powershell-scripts-with-psscriptanalyzer/
ps_script_analyzer:
  stage: test
  image: mcr.microsoft.com/powershell:lts-debian-11
  tags:
    - k8s
  before_script:
    - pwsh -Command "Set-PSRepository -ErrorAction Stop -InstallationPolicy Trusted -Name PSGallery -Verbose"
    - pwsh -Command "Install-Module -ErrorAction Stop -Name PSScriptAnalyzer -Verbose -Repository PSGallery -Confirm:$False"
  script:
    - pwsh -Command "Invoke-ScriptAnalyzer -EnableExit -Recurse -Path . -Severity Error"
  variables:
    POWERSHELL_TELEMETRY_OPTOUT: 1

# TODO
#create_installer:
#  stage: deploy
#  trigger:
#    project: perun-windows/services-installer
#    strategy: depend
#  only:
#    - master
