run_pester_tests:
  image: mcr.microsoft.com/powershell:lts-debian-11
  stage: test
  script:
    - powershell -Command Install-Module -Name Pester -Force
    - powershell -Command Import-Module "Pester" -Force
    - powershell -Command Get-Module Pester | select name,version
    - powershell -Command exit (Invoke-Pester . -Passthru).FailedCount
  variables:
    POWERSHELL_TELEMETRY_OPTOUT: 1

#test_2:
#  before_script:
#    - Import-Module "Pester" -Force
#    - Get-Module Pester | select name,version
#  stage: test
#   script:
#     - exit (Invoke-Pester .\tests\InputChecks -Passthru).FailedCount
#   tags:
#    - windows

# test_3:
#   before_script:
#     - Import-Module "Pester" -Force
#     - Get-Module Pester | select name,version
#   stage: test
#   script:
#     - exit (Invoke-Pester .\tests\ExecutingScripts -Passthru).FailedCount
#   tags:
#    - windows

#create_installer:
#  stage: deploy
#  needs: ["run_pester_tests"]
#  trigger:
#    project: perun-windows/services-installer
#    strategy: depend
#  only:
#    - master
