stages:
  - test
  - package
  - deploy

run_pester_tests:
  before_script:
    - Import-Module "Pester" -Force
    - Get-Module Pester | select name,version
  stage: test
  script:
    - exit (Invoke-Pester . -Passthru).FailedCount
  tags:
   - windows

#test_2:
#  before_script:
#    - Import-Module "Pester" -Force
#    - Get-Module Pester | select name,version
#  stage: test
#   script:
#     - exit (Invoke-Pester .\tests\InputChecks -Passthru).FailedCount
#   tags:
#    - windows

# test_3:
#   before_script:
#     - Import-Module "Pester" -Force
#     - Get-Module Pester | select name,version
#   stage: test
#   script:
#     - exit (Invoke-Pester .\tests\ExecutingScripts -Passthru).FailedCount
#   tags:
#    - windows

create_installer:
  stage: package
  needs: ["run_pester_tests"]
  trigger:
    project: perun-windows/services-installer
    strategy: depend
  only:
    - master